COMPATIBLE_MACHINE_mrzg2ls = "(mrzg2ls)"

PLATFORM_mrzg2ls = "g2l"
EXTRA_FLAGS_mrzg2ls = "BOARD=smarc_pmic_2 SOC_TYPE=1 SPI_FLASH=AT25QL128A"
PMIC_EXTRA_FLAGS_mrzg2ls = "BOARD=smarc_pmic_2"
FLASH_ADDRESS_BL2_BP_mrzg2ls = "00000"
FLASH_ADDRESS_FIP_mrzg2ls = "1D200"
