COMPATIBLE_MACHINE_msrzg2ls = "(msrzg2ls)"

PLATFORM_msrzg2ls = "g2l"
EXTRA_FLAGS_msrzg2ls = "BOARD=smarc_pmic_2 SOC_TYPE=1 SPI_FLASH=AT25QL128A"
PMIC_EXTRA_FLAGS_msrzg2ls = "BOARD=smarc_pmic_2"
FLASH_ADDRESS_BL2_BP_msrzg2ls = "00000"
FLASH_ADDRESS_FIP_msrzg2ls = "1D200"
